name: Reversing.ID
description: Revealing the Truth through Reverse Engineering
exclude: [assets/node_modules, assets/_javascript]
markdown: kramdown
highlighter: rouge
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
permalink: /:year/:month/:day/:slug/

# valid color: white, black, light, dark, primary, link, info, success, warning, success, danger
# default color is primary
tags_color: 
  CTF: danger
  "Open source": warning
  Reversing: dark
  Writeup: info
  Linux: success
plugins:
  - jekyll-seo-tag